// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7FJ2xLTYtf_oPey55qwxSvQw-mRnxAbc',
    appId: '1:606848051526:web:3316684b7ed6b434f51d47',
    messagingSenderId: '606848051526',
    projectId: 'chat-app-8c323',
    authDomain: 'chat-app-8c323.firebaseapp.com',
    storageBucket: 'chat-app-8c323.appspot.com',
    measurementId: 'G-Y0GCRX01HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLW4o4LZ4MJOqtLA9xc9OmRjDWk6tbsSc',
    appId: '1:606848051526:android:cdc4d41d55d8696af51d47',
    messagingSenderId: '606848051526',
    projectId: 'chat-app-8c323',
    storageBucket: 'chat-app-8c323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcc8mZNuiWgG9nPOZj4oNWRsKZXJrBBrM',
    appId: '1:606848051526:ios:a6c4c68f252466d4f51d47',
    messagingSenderId: '606848051526',
    projectId: 'chat-app-8c323',
    storageBucket: 'chat-app-8c323.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcc8mZNuiWgG9nPOZj4oNWRsKZXJrBBrM',
    appId: '1:606848051526:ios:a6c4c68f252466d4f51d47',
    messagingSenderId: '606848051526',
    projectId: 'chat-app-8c323',
    storageBucket: 'chat-app-8c323.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7FJ2xLTYtf_oPey55qwxSvQw-mRnxAbc',
    appId: '1:606848051526:web:af18aa7d1301b36af51d47',
    messagingSenderId: '606848051526',
    projectId: 'chat-app-8c323',
    authDomain: 'chat-app-8c323.firebaseapp.com',
    storageBucket: 'chat-app-8c323.appspot.com',
    measurementId: 'G-5QQDMND33T',
  );

}